### ISSUE TITLE
Add ability to control by 1 button

### ISSUE THREAD

**Issue by goorvy** [gewisser/GyverOLEDMenu#1]
Для добавления возможности управления меню 1 кнопкой в методе void selectNext(boolean isFast = false):
    //if (selectedIdx == (_MS_SIZE - 1)) {
    //  return;
    //}

    //int nextIndex = selectedIdx + 1;

    int nextIndex;
    if (selectedIdx == (_MS_SIZE - 1)) {
      nextIndex = 0;
    } else {
      nextIndex = selectedIdx + 1;
    }

**Comment by goorvy** [comment]
Corrected method selectNext(boolean isFast = false) if menu have more than 1 page.
    if (!indexInCurrentPage(nextIndex)) {
      if (nextIndex < selectedIdx) {
        renderPage(currentPage - 1);
      } else {
        renderPage(currentPage + 1);
      }
      return;
    }

**Comment by gewisser** [comment]
@goorvy Available in latest version
